---
title: "Ingeniería de Datos"
author: "Christian Javier Salas Marquez"
output:
  html_document:
    df_print: paged
  html_notebook: default
  number_sections: yes
  df_print: paged
  toc: yes
  toc_depth: 3
  toc_float: yes
  pdf_document: default
---


```{r}
datos_CENEC <- read.csv("~/Ingenieria Estadistica II PAO 2021/Ingenieria de Datos/Proyecto_SegundoParcial_IngenieriaDeDatos/DATOS_ABIERTOS_ENCUESTA_CENSO_2010/cenec_2010.csv", sep=";")
#View(datos_CENEC)
```


```{r}
anio_inicio_act_princ = datos_CENEC$s4p4c2
anio_const_est = datos_CENEC$s2p5
```



```{r}
anios_act_princ = 2022 - anio_inicio_act_princ
edad_est = 2022 - anio_const_est

```


```{r}
summary(edad_est)
```


***
## PCA
***

```{r}
library(DBI)
library(RMySQL)
library(FactoMineR)
library(factoextra)
library(corrplot)
```


```{r}
p_remu_homb = as.numeric(datos_CENEC$s3p1_1c2)
p_remu_muj = as.numeric(datos_CENEC$s3p1_1c3)
total_homb_ocup = as.numeric(datos_CENEC$s3p1_3c2)
total_muj_ocup = as.numeric(datos_CENEC$s3p1_3c3)
gast_m_remu = as.numeric(datos_CENEC$remu_m)
gast_a_rem = as.numeric(datos_CENEC$gast_rem)
gast_a_mat = as.numeric(datos_CENEC$gast_mat)
gast_a_rac = as.numeric(datos_CENEC$gast_rac)
gast_a_ee = as.numeric(datos_CENEC$gast_ee)
gast_a_com = as.numeric(datos_CENEC$gast_com)
gast_a_ter = as.numeric(datos_CENEC$gast_ter)
egresos = as.numeric(datos_CENEC$egresos)
interes = as.numeric(datos_CENEC$interes)
tax = as.numeric(datos_CENEC$tax)
ingresos = as.numeric(datos_CENEC$ingresos)
otr_ing = as.numeric(datos_CENEC$otr_ing)
ing_ext = as.numeric(datos_CENEC$ing_ext)
```



```{r}
datos_PCA = data.frame(p_remu_homb, p_remu_muj, total_homb_ocup, total_muj_ocup, gast_m_remu, gast_a_rem, gast_a_mat, gast_a_rac, gast_a_ee, gast_a_com, gast_a_ter, egresos, interes, tax, ingresos, otr_ing, ing_ext)
```

```{r}
str(datos_PCA)

na.omit(datos_PCA)
```


```{r}
datosAnalisis = scale(na.omit(datos_PCA))

```


```{r}

#Analisis de Factores
res.pca <- PCA(datosAnalisis,scale.unit = TRUE,ncp=8,graph = FALSE)
eig.val <- get_eigenvalue(res.pca)



#Elegir el numero de componentes principales
fviz_eig(res.pca, addlabels = TRUE, ylim = c(0, 100))

```




### Representacion de variables
```{r}
#Reprsentacion de obervaciones y variables
fviz_pca_var(res.pca, col.var = "black")

```


### Cluster 
```{r}
#Cluster Usando el algoritmo de Ward
res.hcw <- hclust(dist(datosAnalisis[1:1000,])) #Por limitación del CPU y Memoria RAM, elijo solo los 1000 primeros valores

#fviz_dend(res.hcw, k = 4, # Cut in four groups
#          cex = 0.5, # label size
#          k_colors = c("#2E9FDF", "#00AFBB", "#E7B800", "#FC4E07","#8835DC"),
#          color_labels_by_k = TRUE, # color labels by groups
#          rect = TRUE # Add rectangle around groups
#)


```



### Matriz de Correlaci&oacute;n entre las componentes y variables

```{r}
var <- get_pca_var(res.pca)
corrplot(var$cos2, is.corr=FALSE)
```

### Ventas Biplot - Linea de productos por Ciudades

```{r}
#Grafica de Biplot - Filas y Columnas
fviz_pca_biplot(res.pca, repel = FALSE,
                col.var = "#00AFBB", # Variables color
                col.ind = "#F5552E" # Individuals color
                , select.var = list(cos2 = 0.6)
)
```


### Cluster de ventas por ciudades (Convexo)
```{r}
grp <- cutree(res.hcw, k = 3)
fviz_cluster(list(data = datosAnalisis, cluster = grp),
             palette = c("#2E9FDF", "#E7B800", "#8835DC"),
             ellipse.type = "convex", # Concentration ellipse
             repel = FALSE, # Avoid label overplotting (slow)
             show.clust.cent = FALSE, ggtheme = theme_minimal())


```




```{r}
library(corrplot)
corrplot(cor(datos_PCA))
```


```{r}
pca <- prcomp(datosAnalisis)
```



```{r}
summary(pca)
```


```{r}
library(tidyverse)
library(highcharter) 

```



```{r}

hc <- hchart(pca)
hc
```





```{r}
fit.lm <- lm(na.omit(datos_CENEC$ingresos) ~ na.omit(datos_CENEC$s6p10_1))
```








